### ISSUE TITLE
App crashing on Android 12.1

### ISSUE THREAD

**Issue by OshekharO** [hoc081098/ComicReaderApp_MVI_Coroutine_RxKotlin_Jetpack#80]
**Describe the bug**
App is crashing on startup.

**To Reproduce**
1. Click on app icon
2. See error

**Expected behavior**

**Logs**
[https://paste.evolution-x.org/6ic4xi](https://paste.evolution-x.org/6ic4xi) 

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8 Pro
 - OS: Android 12.1
 - Browser: Chrome
 - Version: Latest

**Additional context**

**Comment by hoc081098** [comment]
Hi @OshekharO,  thanks for reporting, could you tell me which branch you have  checked out?

**Comment by OshekharO** [comment]
@hoc081098 i have downloaded directly from ( master / debug app )

**Comment by hoc081098** [comment]
It seem to be https://issuetracker.google.com/issues/230454566 and https://github.com/square/leakcanary/issues/2314

**Comment by OshekharO** [comment]
Still this issue exist in latest Debug app
